#!/bin/bash

if [ ! -f "$1" ]; then
    echo "$1 is not a valid file"
    exit 0
fi

filename=$(basename -- "$1")
extension="${filename##*.}"
base="${filename%.*}"

if [ ! "$extension" = "hs" ]; then
    echo "$1 is not a Haskell source file"
    exit 0
fi

test_file="${base}Test.${extension}"
script_dir=$(dirname "$0")

if [ ! -f "${script_dir}/${test_file}" ]; then
    echo "$1 does not have a test associated with it"
    exit 0
fi

tmp_dir=$(mktemp -d)

cp -r "${script_dir}/Mooc" "$tmp_dir"
cp "${script_dir}/${test_file}" "$tmp_dir"
cp "$1" "$tmp_dir"

cd $tmp_dir
runhaskell "$test_file"

rm -rf $tmp_dir
